### ISSUE TITLE
Scene Tiling: Segmentation with Semantics 为什么不直接pool1D再取top-k呢

### ISSUE THREAD

**Issue by foreverpiano** [bigai-nlco/VideoLLaMB#1]
![图片](https://github.com/user-attachments/assets/6db456fc-8888-4b58-8003-238540eb5df1)
不太懂这一套和先相邻的作差，然后pool1D smooth下，然后求top-k的区别

**Comment by patrick-tssn** [comment]
page这里可能没有写清楚，top-k 只是一种防止OOM的备选项，实际上第3步就是自适应计算整段video的threshold，按照这个threshold，是可以获得动态数量的segment的，不需要 top-k。

**Comment by patrick-tssn** [comment]
关于为什么不用相邻的差值，我们这套可以 refer 经典的 texttilling: https://aclanthology.org/J97-1003.pdf
简而言之就是使用贪心计算一个语义上的”沟“，这个”沟“越深，越可能发生切换。如果只考虑相邻的差值+pool还是不够平滑。

**Comment by foreverpiano** [comment]
OK明白
