### ISSUE TITLE
About STREAMING CAPTION

### ISSUE THREAD

**Issue by jun0wanan** [bigai-nlco/VideoLLaMB#3]
Hello,

Thank you for sharing such excellent code; it looks very solid overall! I'm particularly interested in the stream module. I'm curious how it works without needing an EOS prediction—what mechanism does it use? For instance, does it output a caption as soon as it detects a change in the video frames? I was wondering if you could explain this in more detail, as it's not fully covered in the paper.

Hope to get your reply :>!

Best wishes

**Comment by patrick-tssn** [comment]
Thank you for your interest! This is actually a product of our SceneTilling Algorithm (Section 2.1). If you are familiar with streaming video captioning (https://arxiv.org/abs/2404.01297), you'll find that the EOS in these works is labeled by the end of an action. During inference, they predict the eos with a tunable threshold. I think these strategies are similar to the rules ;-). Therefore, in this work, instead, we use the SceneTilling Algorithm to automatically detect the possible transition points of video scenes and predict captions at these transition points. I hope my explanation addresses your confusion.

**Comment by jun0wanan** [comment]
> Thank you for your interest! This is actually a product of our SceneTilling Algorithm (Section 2.1). If you are familiar with streaming video captioning (https://arxiv.org/abs/2404.01297), you'll find that the EOS in these works is labeled by the end of an action. During inference, they predict the eos with a tunable threshold. I think these strategies are similar to the rules ;-). Therefore, in this work, instead, we use the SceneTilling Algorithm to automatically detect the possible transition points of video scenes and predict captions at these transition points. I hope my explanation addresses your confusion.

Thanks !

**Comment by jun0wanan** [comment]
你好，

最近拿您这个方法测其他数据集，类似的也是longvideo（有超过600s的视频）效果感觉比不过目前最新的qwen2vl和llava-video（64帧和32帧），我想请教一下，如果把只是把llm（改成qwen2）和vision encoder（改成siplip），重新安装您的训练数据配比来训练一个模型，相当于只用您的memory方法，您觉得有希望比您现在这个模型再提高吗？您有什么建议吗？或者说您当前的模型我可以怎么不修改train，只是改比如帧数或者memorytoken什么的能有提高？

希望得到您的回答，因为我认为您的整体方法还是比较solid的

**Comment by jun0wanan** [comment]
> 你好，
> 
> 最近拿您这个方法测其他数据集，类似的也是longvideo（有超过600s的视频）效果感觉比不过目前最新的qwen2vl和llava-video（64帧和32帧），我想请教一下，如果把只是把llm（改成qwen2）和vision encoder（改成siplip），重新安装您的训练数据配比来训练一个模型，相当于只用您的memory方法，您觉得有希望比您现在这个模型再提高吗？您有什么建议吗？或者说您当前的模型我可以怎么不修改train，只是改比如帧数或者memorytoken什么的能有提高？
> 
> 希望得到您的回答，因为我认为您的整体方法还是比较solid的

还有我比较好奇的是，为什么llm要用vicunav1.5,单纯是为了和pllava对比吗？

**Comment by patrick-tssn** [comment]
Hello，按照我的经验，这个方法因为改了 vision 的 representation，和 resampler-based 方法比如之前的 Qformer/Flamingo 比较接近，这种在下游任务的效果是不如用 pooling/visual patch feature similarity 压缩这种 normalize 的方法的（虽然我觉得后者没什么insight，但是确实效果好 hhh）。从另一个角度看，我觉得更公平的比较方法是算 visual input 的压缩比，就是实际输入到 LLM 的压缩后的 feature 长度 / 原始视频长度。

**Comment by patrick-tssn** [comment]
用vicuna1.5纯粹是因为这个工作是四五月做的，当时最好的就是PLLaVA，为了公平比较就和他一样。

**Comment by jun0wanan** [comment]
> Hello，按照我的经验，这个方法因为改了 vision 的 representation，和 resampler-based 方法比如之前的 Qformer/Flamingo 比较接近，这种在下游任务的效果是不如用 pooling/visual patch feature similarity 压缩这种 normalize 的方法的（虽然我觉得后者没什么insight，但是确实效果好 hhh）。从另一个角度看，我觉得更公平的比较方法是算 visual input 的压缩比，就是实际输入到 LLM 的压缩后的 feature 长度 / 原始视频长度。

 明白了，谢谢哈~所以现在的论文都是token压缩上hh

**Comment by jun0wanan** [comment]
> 用vicuna1.5纯粹是因为这个工作是四五月做的，当时最好的就是PLLaVA，为了公平比较就和他一样。

还想请教您一个问题，当前代码是基于llava那份代码改的是吗，我看文件夹什么的都很像

**Comment by patrick-tssn** [comment]
是结合了 [LLaVA](https://github.com/haotian-liu/LLaVA) 和 [Video-LLaVA](https://github.com/PKU-YuanGroup/Video-LLaVA)，不过这两个repo都不再更新了，所以我建议可以在 [LLaVA-NeXT](https://github.com/LLaVA-VL/LLaVA-NeXT) 上改动，感觉他们在做长期维护，会添加新的LLM template，会修 distribute 的 bug。当然这几个逻辑都差不多，就是 encoder，image/patch process上区别比较大。

**Comment by jun0wanan** [comment]
> 是结合了 [LLaVA](https://github.com/haotian-liu/LLaVA) 和 [Video-LLaVA](https://github.com/PKU-YuanGroup/Video-LLaVA)，不过这两个repo都不再更新了，所以我建议可以在 [LLaVA-NeXT](https://github.com/LLaVA-VL/LLaVA-NeXT) 上改动，感觉他们在做长期维护，会添加新的LLM template，会修 distribute 的 bug。当然这几个逻辑都差不多，就是 encoder，image/patch process上区别比较大。

明白了，还有一个问题想咨询的，就是我debug时候看那个segment函数，是固定提取topk吗？k=3，但是有个问题我看外层是把 b和t进行合并了，这样相当于一个batch提取前k个segment？这样感觉有点奇怪还是我搞错了。
难道不应该是batch里面每个例子提取topk吗

**Comment by patrick-tssn** [comment]
topk 是超参，我试了4效果比较好，其实可以不用指定k，按照均值和标准差来自动算k。至于b和t的逻辑，是因为要对每一个视频做segment，我没写batch的代码，就在process里面循环处理每一个视频，所以 batch 一定为 1，参考`VideoLLaMB/llava/model/llava_arch.py` line 505-506

**Comment by jun0wanan** [comment]
> topk 是超参，我试了4效果比较好，其实可以不用指定k，按照均值和标准差来自动算k。至于b和t的逻辑，是因为要对每一个视频做segment，我没写batch的代码，就在process里面循环处理每一个视频，所以 batch 一定为 1，参考`VideoLLaMB/llava/model/llava_arch.py` line 505-506

感谢您的及时回复。
也就是说目前在最外层时候是batch中一个个样例这样处理的，目的是如果使用的是k自动计算时候，每个样例不一样所以要分开处理。最后进行pad和截断处理后变成batch输入进llm，不知道是这样吗
还想确认一下的是，当前训练时候是均匀抽取16帧，然后分seg为4，也就是每个memorytoken压缩了4帧。测试时候frame最好情况是32，也就是每个memorytoken压缩了8帧，压缩率目前是4倍。好奇您有试过将这个帧数增加来测试或者训练吗，还是只是为了对标pllava，才这么选取的。

**Comment by patrick-tssn** [comment]
你理解的没错；训练测试我都试过增加frame，实验结果显示收益不高，就没有调这个了。感觉根本原因还是这里memory没有学的很好。

**Comment by jun0wanan** [comment]
> 你理解的没错；训练测试我都试过增加frame，实验结果显示收益不高，就没有调这个了。感觉根本原因还是这里memory没有学的很好。

o(╥﹏╥)o你的意思是这个memory不太好吗，可是看起来方法还挺简单的效果也不错。

压缩类的如果要训练的，其实也算是改了 vision 的 representation，除非是training-free的

**Comment by patrick-tssn** [comment]
同比是很不错，就是环比比不过压缩方法，压缩就是线性组合，我理解不算改动，或者改动不是非常大。这个方向很多审稿人只关注最终的结果，并不 care fair comparison，社区更是这样，downstream 效果好的方法对开发者来说就是好的方法。回到这个问题，压缩方法有一个非常显然的缺点，就是会破坏连续的视觉特征，不知道 resampler/memory-based 的方法在一些对这方面要求比较高的任务（比如偏OCR的）会不会有优势🤔。

**Comment by jun0wanan** [comment]
> 同比是很不错，就是环比比不过压缩方法，压缩就是线性组合，我理解不算改动，或者改动不是非常大。这个方向很多审稿人只关注最终的结果，并不 care fair comparison，社区更是这样，downstream 效果好的方法对开发者来说就是好的方法。回到这个问题，压缩方法有一个非常显然的缺点，就是会破坏连续的视觉特征，不知道 resampler/memory-based 的方法在一些对这方面要求比较高的任务（比如偏OCR的）会不会有优势🤔。

好滴，感谢您和我讨论，我先试试实验加入最新的模型看看。

**Comment by patrick-tssn** [comment]
我的wx是 Wang-jc1996 如果你对这个比较感兴趣的话我们可以多多讨论与合作～

**Comment by jun0wanan** [comment]
> 我的wx是 Wang-jc1996 如果你对这个比较感兴趣的话我们可以多多讨论与合作～

好的~(u‿ฺu✿ฺ)

**Comment by jun0wanan** [comment]
> 我的wx是 Wang-jc1996 如果你对这个比较感兴趣的话我们可以多多讨论与合作～

您好我想咨询一下：
```
steps = torch.linspace(index, bi, min(8, bi-index+1), dtype=torch.int).to(image_features.device)
hidden_state = torch.index_select(image_features, 0, steps)
```
这个代码代表每个事件分块最多不超过8帧，不知道是不是这个意思？那就意味着，最后输入进llm的是，最后一个事件假设最多取了8帧特征（变成token）+融合之前历史的特征。emmm这样是不是太少了信息

**Comment by patrick-tssn** [comment]
是滴，这个8是因为这里的encoder用的是ImageBind里的video encoder，这个里面有temporal encoding，限制video length只能是8。当然你可以用clip/siglip，这样就可以没有这个限制了。
