### ISSUE TITLE
Instruction Tuning Json

### ISSUE THREAD

**Issue by YiwuZhong** [bigai-nlco/VideoLLaMB#5]
@patrick-tssn Thanks for your previous help. 

I was wondering if it is possible to release the script for creating instruction tuning JSON files in this work, e.g., converting PLLaVA's jsons into the ones in this work.

Yiwu

**Comment by patrick-tssn** [comment]
There are three steps in this preprocessing:

1. Filter out videos that can't be loaded by decord in videochatgpt.
2. Convert multiple-choice QA to align with the llava-1.5 instruction format by removing the answer in the options.
3. Merge with llava-1.5 instruction tuning data.

Here is the code:

1. Filter out videos that can't be loaded by decord.
```bash
ls > videochatgpt.txt # get videochatgpt files
```
```python
import decord
from decord import cpu
decord.bridge.set_bridge("torch")
from tqdm import tqdm

vids
with open('videochatgpt.txt') as fp:
    for line in fp.readlines():
        vid = line.split('/')[-1].split('.')[0]
        vids.append(vid)

fail_path = []
for vid in tqdm(vids):
    video_path = f"{vid}.mp4"  
    try:
        video_reader = decord.VideoReader(video_path)   
        vlen = len(video_reader)
    except:
        fail_path.append(video_path)

print(len(fail_path))
with open('videochatgpt_path_failcode.txt', 'w') as fp:
    for itm in fail_path:
        fp.write(itm+'\n')
```

2. Convert multiple-choice QA to align with the llava-1.5 instruction format by removing the answer in the options.
```python
# classification/k710, classification/ssv2, reasoning/next_qa, reasoning/clevrer_mc, reasoning/clevrer_qa
new_train = []
with open("magic_jsons/video/classification/k710/train.json") as jp:
    train = json.load(jp)
for dct in train:
    for qa in dct["QA"]:
        a = qa["a"]
        a = a.split()[1].strip('()')
        qa["a"] = a

        q = qa["q"]
        options = q.replace("Options:\n", '').split('\n')
        new_options = []
        for option in options:
            new_option = option.replace('(', '').replace(')', '.')
            new_options.append(new_option)
        new_question = "Options:\n" + "\n".join(new_options) + "\nAnswer with the option's letter from the given choices directly."
        qa["q"] = new_question
    new_train.append(dct)
with open("magic_jsons/video/classification/k710/new_train.json", "w") as jp:
    train = json.dump(new_train, jp)
```

3. Merge with llava-1.5 tuning data.
```python
# load list then add
```

I hope you find this helpful.

**Comment by YiwuZhong** [comment]
Thanks for your detailed information!

I also noticed that for videos, the original 'QA' is replaced by `'conversations'`, and the content `'from': 'human', 'value': '<video>\nxxxx`. Are these only changes? There is an `id` field in json. How does it derive?

**Comment by patrick-tssn** [comment]
Yes, the format change and the special token `<video>` are used to match the llava code. The id is not utilized in this code, so it can be omitted.
