### ISSUE TITLE
The difference between `finetune_video_image.slurm` and `finetune_video_image_loss.slurm`.

### ISSUE THREAD

**Issue by Code-kunkun** [bigai-nlco/VideoLLaMB#7]
Thank you for your outstanding work! However, I encountered some issues during the reproduction process, and I would like to ask about the difference between the `finetune_video_image.slurm` and `finetune_video_image_loss.slurm` scripts. As mentioned in issue #4, `finetune_video_image.slurm` will call `LlavaLlamaForCausalLM`, while `finetune_video_image_loss.slurm` will call `LlavaLlamaForCausalLMRMT`. If it calls `LlavaLlamaForCausalLM`, it seems to be just the standard Llava structure without involving the designs like memory bridge layers. Could you please clarify which script corresponds to the structure described in the paper?

**Comment by patrick-tssn** [comment]
Thank you for your interest—this is a great question. The recurrent mechanism is implemented in the projector, and you can refer to `llava_arch.py#encode_video` and `multimodal_projector/rmt_r_transformer_projector.py` for details. Regarding `LlavaLlamaForCausalLMRMT`, it is actually an advanced version of the model presented in our paper, which we haven't reported in the current arxiv version. This version introduces an additional loss for each recurrent step, whereas `LlavaLlamaForCausalLM` calculates the loss only for the final recurrent step (which may have a higher likelihood of gradient-related issues).

**Comment by Code-kunkun** [comment]
Thanks for your quick reply!!!
